### ISSUE TITLE
Tab bar controller

### ISSUE THREAD

**Issue by putorti** [highperch/polipicks#2]
Something seems wrong with the tab bar view controller. I'm trying to create a relationship between the views and the tab bar, and then get the icons in, but the 'relationship' option doesn't exist.

**Comment by justinpeng** [comment]
@putorti It shouldn't be necessary to create a relationship between the VCs and the tab bar. There's code to instantiate and present them programatically when the proper button is selected.

**Comment by justinpeng** [comment]
Fixed with change to generic tab bar controller
